project_id = "tdxepwdtdeqwoucqlaru"

[functions.generate-questions]
verify_jwt = false

[functions.generate-explanation]
verify_jwt = false

[functions.analyze-explanation]
verify_jwt = false

[functions.challenge-thinking]
verify_jwt = false